### PR TITLE
Notebook format, buttons, and setup

### PR DESCRIPTION
**Pull request by lamberta**
Add license, buttons, and setup to install packages.
Apply `nbfmt` to notebooks.

### CODE REVIEW

**Comment by mpharrigan** [comment]
Can we do nbfmt with 1 space to prevent these huge diffs?

**Comment by lamberta** [comment]
> Can we do nbfmt with 1 space indent to prevent these huge diffs?

Right now the ReCirq notebooks are a mix of 1 and 2 spaces. This PR makes them all 2 to make it consistent, but I can make them all 1, if you prefer. You'll still get some large diffs in this PR but shouldn't going forward. I believe Cirq went with 1, as well.

**Comment by lamberta** [comment]
Will need to rebase with https://github.com/quantumlib/ReCirq/pull/89

**Comment by mpharrigan** [comment]
Let's do all 1 space indents for sure.

If possible, can you have the automated nbfmt changes in a separate commit so I can tell if it's just the indent level changing vs. any additional changes (buttons, setup, ...)

**Comment by lamberta** [comment]
Yeah, sounds good. Lemme get the nav in order and then I'll come back to this PR. I'll split up the nbfmt and the button changes to make it easier to review

**Pull request closed without merging**
