### PR TITLE
Format quantum_chess_rest_api.ipynb

### PR DESCRIPTION
**Pull request by lamberta**
Add cell to disable local webserver in docs infra.

### CODE REVIEW

**Review by mpharrigan — APPROVED** [review]
lgtm

do we eventually want to put a `try: import` guard around the flask pip installs? If we're not executing the web server, should we skip executing the flask-install and flask server definition cells as well? To save time when executing the notebook in the CI

**Comment by mpharrigan** [comment]
Debugging build failure in https://github.com/quantumlib/ReCirq/issues/104

**Comment by lamberta** [comment]
The server is still run in Colab, just not when converting to Markdown for the site now.

Probably need to keep the pip installs since we still need it to define the routes for the webserver. But, as far as GItHub Actions CI goes, may want to guard that final `app.run()` if it's causing things to hang. Alternatively, could make that a code formatted section within a text cell, but that would not execute anywhere.

**Review by dstrain115 — APPROVED** [review]

**Comment by mpharrigan** [comment]
@lamberta can you merge in master to pick up https://github.com/quantumlib/ReCirq/pull/105 which will fix the CI

**Comment by lamberta** [comment]
@mpharrigan Rebased and looks like it worked. Thanks!

**Pull request merged**
