### PR TITLE
Fix failing Fermi-Hubbard experiment example

### PR DESCRIPTION
**Pull request by rmlarose**
The final portion of the notebook demonstrates how to use the QCS. To fix the authentication error I defaulted to a simulator:

```python
try:
    engine_sampler = cirq.google.get_engine_sampler(
        processor_id="rainbow", gate_set_name="sqrt_iswap"
    )
except OSError:
    # Use the simulator as a backup.
    engine_sampler = cirq.Simulator()
```

 Other options are possible, let me know what you think.

### CODE REVIEW

**Comment by mpharrigan** [comment]
It's strange to expect `OSError` to signal lack of authentication. In practice, this is because the actual line that fails is looking for the google cloud environment variable. What if the conditional was instead 

```python
if 'GOOGLE_CLOUD_PROJECT' in os.environ:
  blah
else:
  simulator
```

**Review by mpharrigan — APPROVED** [review]
looks good. one suggestion in the thread for your consideration

**Comment by rmlarose** [comment]
> ```python
> GOOGLE_CLOUD_PROJECT
> ```

I like it!

**Comment by rmlarose** [comment]
Unfortunate random failure due to #97. Changed files should be ok to merge still.

**Review by mrwojtek — APPROVED** [review]

**Pull request merged**
