### PR TITLE
Move beyond classical random circuits into ReCirq

### PR DESCRIPTION
**Pull request by dstrain115**
- These experiments probably belong in ReCirq and not in
      cirq.experiments.

See [cirq#3327](https://github.com/quantumlib/Cirq/issues/3327)

### CODE REVIEW

**Comment by mpharrigan** [comment]
can we take this opportunity to change the module and function names to avoid "supremacy" and use "beyond classical"?

**Comment by dstrain115** [comment]
> can we take this opportunity to change the module and function names to avoid "supremacy" and use "beyond classical"?

Done!  PTAL!

**Review by mpharrigan — APPROVED** [review]

**Comment by mpharrigan** [comment]
Looks fine. I always find these circuits a little confusing because they correspond to the 2018 theory work https://www.nature.com/articles/s41567-018-0124-x and are subtly different from the circuits used in the experimental demonstration https://www.nature.com/articles/s41586-019-1666-5

**Comment by dstrain115** [comment]
Thanks for the review.  We can revisit them and maybe add the newer circuit, but these are the ones from cirq.
This unblocks removing them from cirq, and we can always add more stuff (or extra explanation) to this directory now.

**Pull request merged**
