### PR TITLE
[WIP] Add QCQMC code and notebooks.

### PR DESCRIPTION
**Pull request by fdmalone**
- [x] Add existing code and notbooks to recirq
- [x] Enable testing
- [x] Add notebook which pulls Zenodo repo and reproduced paper results
- [x] Add README

### CODE REVIEW

**Comment by fdmalone** [comment]
cc @linusjoonho

**Comment by fdmalone** [comment]
I will split this up into ~ 5 PRs. This is the final state roughly with the tests passing locally on my machine.

**Comment by fdmalone** [comment]
Screenshot 2024-06-11 at 1 39 11 PM

**Comment by mpharrigan** [comment]
Make sure to add a new directory to `docs/qcqmc` with a file `index.md` that gives a brief introduction to the paper/experiment this code was used for and crucially has a link to the paper itself

**Comment by fdmalone** [comment]
closing this following #357. Phew. @wjhuggins please update as appropriate for better docs around shadow tomography.

**Pull request closed without merging**
