### PR TITLE
Fix setup.py to read from requirements.txt

### PR DESCRIPTION
**Pull request by yashk2810**

### CODE REVIEW

**Comment by yashk2810** [comment]
@lamberta @mpharrigan PTAL

**Comment by lamberta** [comment]
Need this to install requirements with the package (using git install since package not on pypi):

```
$ pip install git+https://github.com/quantumlib/ReCirq
```

**Comment by lamberta** [comment]
cc: @dstrain115

**Comment by mpharrigan** [comment]
This is ok for now, but as we collect more example applications; each with their own set of bespoke dependencies, I'd like to have more fine-tuned dependency management so `pip install recirq` doesn't download everything under the sun

**Comment by yashk2810** [comment]
> doesn't download everything under the sun

Sure you can always use `extra_requires` for that: https://github.com/tensorflow/docs/blob/master/setup.py#L60

**Pull request merged**
