### PR TITLE
Fix a small potential bug of import DEFAULT_RESOLVERS from cirq.

### PR DESCRIPTION
**Pull request by Spaceenter**

### CODE REVIEW

**Comment by mpharrigan** [comment]
What's the bug here?

**Comment by EDDahl** [comment]
For me this was more than a potential bug.  It was a real bug.

I did a fresh build of recirq and then issued these commands in my ipython session:

```
import networkx as nx
import numpy as np
import scipy.optimize
import cirq
```
So far, so good.  Then the failure happened on the next import:

`import recirq
Traceback (most recent call last):
  File "/Users/ddahl/venvs/Cirq/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-90c7f2ee5a60>", line 1, in <module>
    import recirq
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/ddahl/venvs/Cirq/lib/python3.7/site-packages/recirq/__init__.py", line 15, in <module>
    from recirq.serialization_utils import (
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/ddahl/venvs/Cirq/lib/python3.7/site-packages/recirq/serialization_utils.py", line 226, in <module>
    + protocols.DEFAULT_RESOLVERS
AttributeError: module 'cirq.protocols' has no attribute 'DEFAULT_RESOLVERS'
`

I manually applied the patch from @Spaceenter 's branch and tried again.  The AttributeError went away.

**Comment by Spaceenter** [comment]
> What's the bug here?

See the file changed -- basically the import path of DEFAULT_RESOLVERS is wrong.
(Sorry for the late reply, somehow I stopped getting notification email from github...)

**Comment by mpharrigan** [comment]
Sorry, I don't see what's wrong about it. The import works locally for me and on the unit tests, so please understand my confusion

**Comment by mpharrigan** [comment]
What version of Cirq are y'all using?

**Comment by EDDahl** [comment]
I git cloned from the repo this morning.

**Comment by Spaceenter** [comment]
>>> import cirq
>>> cirq.__version__
'0.7.0'

for me

@mpharrigan

**Comment by EDDahl** [comment]
BTW, after the pip install, I went on to docs to "make html".

I had to specify "pytket==0.1.6 --no-deps" to avoid dependency problems.

This uncovered a dependency on pandoc which I proceeded to find & install.

At this point, "make html" got a bit further, but then encountered:

    reading sources... [ 15%] qaoa/Tasks-Tutorial

which seemed to take way too long.  I went away to read a paper
on QAOA and came back after an hour.  Apparently that step had
finished, but there were two more errors:

/Users/ddahl/ColdQuanta/Dev/recirq/docs/qaoa/Example-Problems.ipynb:45:
WARNING: Block quote ends without a blank line; unexpected unindent.

and:

ModuleNotFoundError: No module named 'seaborn'

The latter was easy to fix.  I'm assuming there's some small typo in the
Example-Problems notebook.

**Comment by mpharrigan** [comment]
To all those having problems: try using the pinned dev version of cirq in `requirements.txt`. 

> I git cloned from the repo this morning.

I meant *cirq* version, not recirq (this repository). 

> I had to specify "pytket==0.1.6 --no-deps" to avoid dependency problems.

Yes, that's an unfortunate limitation of that release of pytket. We should document it somewhere (right now, the source of truth is `.github/workflows/pythonpackage.yml` which is how the CI actually runs)

> which seemed to take way too long.

This runs the entire experiment end-to-end, so yeah it will take a while. We should warn people about this. if you set the environment variable `NBSPHINX_EXECUTE_NOTEBOOKS=auto` it will use the already-filled-in notebook included with the repository

> WARNING: Block quote ends without a blank line; unexpected unindent.

This can be safely ignored and there's no way to fix it, as far as I can tell

> ModuleNotFoundError: No module named 'seaborn'

`seaborn` is now included in `requirements.txt`

**Comment by mpharrigan** [comment]
Closing this since Cirq 0.8 has been released and we've pinned to that

**Pull request closed without merging**
