### PR TITLE
Add Hartree-Fock VQE experiment (move from OpenFermion-Cirq)

### PR DESCRIPTION
**Pull request by kevinsung**
This adds the code from OpenFermion-Cirq essentially unchanged, except for the following:
- Fixed formatting
- Fixed lint
- Added copyright and license notices
- Renamed some test files to match the names of the tested files
- Converted docstrings from reST style to Google style

I realize that this code requires further cleanup, but I see no harm in merging this PR and performing cleanup later, especially since this move is required to deprecate OpenFermion-Cirq.

### CODE REVIEW

**Comment by ncrubin** [comment]
You might want to get @mpharrigan sign off as well.

**Comment by kevinsung** [comment]
Yeah, I'd like @mpharrigan to take a look too.

**Comment by mpharrigan** [comment]
Let's merge this after #52 . I'm fine porting more-or-less verbatim; then I want to go through all the documentation, open issues, and we can start grinding through fixing them.

**Comment by kevinsung** [comment]
@mpharrigan #52 has been merged so I'm going to go ahead with this.

**Pull request merged**
