### PR TITLE
Add QCQMC to cards / TOC on quantumai website.

### PR DESCRIPTION
**Pull request by fdmalone**

### CODE REVIEW

**Review by pavoljuhas — APPROVED** [review]
yamllint reports some indentation errors on those files, so please consider 258cb4175d00a3c55d823bb465b7a1869162d67a
```
$ git pull --ff-only https://github.com/pavoljuhas/ReCirq.git amend-pr-363
```

Otherwise LGTM.

**Comment by fdmalone** [comment]
Done.

**Comment by pavoljuhas** [comment]
Confirming QCQMC shows at the bottom of https://quantumai.google/cirq/experiments and in the LHS TOC.   Yay!

**Comment by fdmalone** [comment]
You read my mind, I was just about to check lol. Thanks!

**Pull request merged**
