### PR TITLE
Some QML LFE nits

### PR DESCRIPTION
**Pull request by tonybruguier**

### CODE REVIEW

**Comment by mpharrigan** [comment]
cc @MichaelBroughton

**Comment by mpharrigan** [comment]
@MichaelBroughton can you review

**Review by MichaelBroughton — APPROVED** [review]

**Comment by mpharrigan** [comment]
I don't know why none of the CI checks are running

**Comment by mpharrigan** [comment]
@tonybruguier can you try merging master and pushing to trigger the CI

**Comment by tonybruguier** [comment]
@mpharrigan Like so?

**Comment by mpharrigan** [comment]
yes, thanks

**Pull request merged**
