### PR TITLE
QCQMC Part 4 

### PR DESCRIPTION
**Pull request by fdmalone**
Adds the shadow tomography module.

Depends on #342 and #343

### CODE REVIEW

**Comment by fdmalone** [comment]
cc @mpharrigan

cc @wjhuggins: https://github.com/quantumlib/ReCirq/pull/346/commits/7f5ae44132002afa4800eef7d62e279c7fb6bfcb#diff-413ef535e04fd816dbfef4b013ff25cf7b923daf4ab6ef74832b66977f2a0ff9R35 etc, there are a bunch of ????? in the docstrings. Please advise

**Comment by wjhuggins** [comment]
I don't know why they don't appear here, but I added inline comments in the file at the link to the diff. Would you like me to draft some new docstrings? How much detail should we add to the shadow tomography piece? One option would be to go light on the detail but add a demo notebook that explains things a bit more. I could whip that up.

**Comment by fdmalone** [comment]
Examples are probably better. I'll tag you in an issue. It can go in after everything else is merged.

**Comment by fdmalone** [comment]
@mpharrigan / @wjhuggins PTAL

**Review by mpharrigan — APPROVED** [review]

**Pull request merged**
